// <auto-generated />
using System;
using TENANTFRAMEWORK.Persistence.EF.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TENANTFRAMEWORK.Persistence.EF.SQL.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            
#pragma warning restore 612, 618
        }
    }
}
